title: 개발하며 Nolsigan
description: Nolsigan's personal blog

url: http://nolsigan.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
#  - title: Contact
#    url: /contact

social:
   github: nolsigan
   email: hiayuna@snu.ac.kr

google_analytics: "UA-77722850-1"
