# Jekyll Defaults
title: 개발하며 nolsigan
description: .
baseurl: "" # the subpath of your site, e.g. /blog

url: "http://nolsigan.github.io"
github: http://github.com/nolsigan

markdown: kramdown
highlighter: rouge
permalink: /post/:title/
paginate: 4
gems: [jekyll-paginate]
paginate_path: "/page:num"
rss_path: feed.xml
tags_path: tag.html
navigation:
- text: About
  url: /about/
- text: Archives
  url: /archives/
- text: Tags
  url: /tags/
